site_name: Flask API
repo_url: https://github.com/luca1801/flask_API
repo_name: luca1801/flask_API
edit_uri: tree/master/docs
site_description: A simple Flask API documentation

theme: 
  name: material
  logo: assets/api.png
  favicon: assets/api.png
  palette:
    primary: green
    accent: light green
  font:
    text: Roboto
    code: Roboto Mono
  
markdown_extensions:
  - attr_list

extra_css:
  - stylesheets/extra.css 